apiVersion: 1

datasources:
  - uid: prometheus
    orgId: 1
    name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: TraceID
    editable: true

  - uid: tempo
    orgId: 1
    name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    jsonData:
      nodeGraph:
        enabled: true
      tracesToLogsV2:
        datasourceUid: loki
        filterByTraceID: true
        filterBySpanID: false
        customQuery: false
        tags:
          - key: service.name
            value: compose_service
    editable: true

  - uid: loki
    orgId: 1
    name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: '(?:trace_id)=(\w+)'
          matcherType: regex
          name: TraceID
          url: '${__value.raw}'
    editable: true
